"""Add is_admin field to User model

Revision ID: b6d35ad241cc
Revises: 98233c85ce1c
Create Date: 2025-10-12 23:47:06.117929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d35ad241cc'
down_revision: Union[str, Sequence[str], None] = '98233c85ce1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Set default value for existing users (not admin)
    op.execute('UPDATE users SET is_admin = 0 WHERE is_admin IS NULL')
    
    # Make the column non-nullable after setting defaults
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
